// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: utils.sql

package database

import (
	"context"
)

const resetAll = `-- name: ResetAll :exec
TRUNCATE TABLE feeds, users, feed_follows CASCADE
`

func (q *Queries) ResetAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAll)
	return err
}
